version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  ApplicationStop:
    - location: deployment_scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
      
  BeforeInstall:
    - location: deployment_scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: deployment_scripts/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: deployment_scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
  
