version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: deployment_scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
      
  BeforeInstall:
    - location: deployment_scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: deployment_scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: deployment_scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
  
